import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { execFileSync } from 'node:child_process';
import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { freshProfile, repoRoot, outputRoot } from './desktop-harness.mjs';
import { bounded, boundedCDP } from './frontend-capture.mjs';
const require = createRequire(import.meta.url);
const { _electron } = require('playwright-core');
const directory = join(outputRoot,'frontend-validation/final/motion'); mkdirSync(directory,{recursive:true});
execFileSync('bun',['build','packages/ui/e2e/frontend-motion.fixture.tsx','--outdir',directory,'--target','browser'],{cwd:repoRoot,stdio:'inherit',windowsHide:true});
writeFileSync(join(directory,'index.html'),'<!doctype html><html lang="zh-CN"><meta charset="UTF-8"><link rel="stylesheet" href="frontend-motion.fixture.css"><body style="margin:0"><div id="root"></div><script type="module" src="frontend-motion.fixture.js"></script></body></html>');
writeFileSync(join(directory,'main.cjs'),`const {app,BrowserWindow}=require('electron'); app.setPath('userData',process.env.YANSIVRA_MOTION_PROFILE); app.whenReady().then(()=>{const w=new BrowserWindow({width:1000,height:760,show:false,webPreferences:{backgroundThrottling:false,contextIsolation:true,sandbox:true,nodeIntegration:false}});w.loadFile(process.env.YANSIVRA_MOTION_HTML);});app.on('window-all-closed',()=>app.quit());`);
const env = { ...process.env,YANSIVRA_MOTION_PROFILE:freshProfile('动效组件样例 '),YANSIVRA_MOTION_HTML:join(directory,'index.html') }; delete env.ELECTRON_RUN_AS_NODE;
const application = await _electron.launch({executablePath:require('electron'),args:[join(directory,'main.cjs')],env,cwd:repoRoot,timeout:45000,recordVideo:{dir:directory,size:{width:1000,height:760}}});
const result = { fixture:true, liveBackend:false, checks:[], frames:[] };
let video;
try {
  const page = await application.firstWindow(); page.setDefaultTimeout(15000); video=page.video(); const cdp=boundedCDP(await page.context().newCDPSession(page));
  await cdp.send('Emulation.setFocusEmulationEnabled',{enabled:true});
  await page.waitForFunction(()=>Boolean(window.yansivraMotionFixture));
  const base={id:'normal-run',symbol:'TEST.US',status:'fetching',startedAt:1,plannedCapabilities:['market.quote','company.financials','company.valuation','research.news'],completedCapabilities:['market.quote'],failedCapabilities:[]};
  const show = run=>page.evaluate(value=>window.yansivraMotionFixture.show(value),run);
  const running = ()=>page.evaluate(()=>document.getAnimations().filter(a=>a.playState==='running').map(a=>({duration:a.effect.getTiming().duration,iterations:a.effect.getTiming().iterations})));
  const capture=async name=>{console.log(`CAPTURE ${name}`);const png=await cdp.send('Page.captureScreenshot',{format:'png',captureBeyondViewport:false});writeFileSync(join(directory,`${name}.png`),Buffer.from(png.data,'base64'));result.frames.push(`${name}.png`);};
  assert.equal(await page.locator('[role="progressbar"]').getAttribute('aria-valuenow'),'0');
  await capture('01-preparing'); await page.waitForTimeout(400);
  await show(base); assert.equal((await running()).length,0); result.checks.push('restored baseline static');
  await show({...base,completedCapabilities:[...base.plannedCapabilities]});
  const lines=await running(); assert.equal(lines.length,2); assert.ok(lines.every(a=>a.duration===420&&a.iterations===1));
  result.checks.push('two real WAAPI lines, 420ms, one iteration'); await capture('02-new-completions'); await page.waitForTimeout(120);
  await show({...base,status:'partial',completedCapabilities:['market.quote','company.financials'],failedCapabilities:['company.valuation']});
  assert.equal((await running()).length,0); result.checks.push('partial terminal cancels live lines'); await capture('03-partial-terminal');
  await page.emulateMedia({reducedMotion:'reduce'}); await show({...base,id:'reduced-run'});
  await show({...base,id:'reduced-run',completedCapabilities:[...base.plannedCapabilities]});
  assert.equal((await running()).length,0); result.checks.push('reduced mode has no live WAAPI lines'); await capture('04-reduced-static');
  await page.emulateMedia({reducedMotion:'no-preference'}); await show({...base,id:'offscreen-run'});
  await show({...base,id:'offscreen-run',completedCapabilities:['market.quote','company.financials']}); assert.equal((await running()).length,1);
  await page.evaluate(()=>{document.getElementById('root').style.marginTop='1600px';}); await page.waitForTimeout(100);
  assert.equal((await running()).length,0); result.checks.push('actual IntersectionObserver cancels offscreen line');
  await page.evaluate(()=>{document.getElementById('root').style.marginTop='0';}); await page.waitForTimeout(100); assert.equal((await running()).length,0);
  await show({...base,id:'conflict-run',completedCapabilities:['market.quote','company.financials'],failedCapabilities:['company.financials']});
  assert.equal(await page.locator('[data-testid="research-flow-map"]').getAttribute('data-inconsistent'),'true');
  await show({...base,id:'conflict-run',completedCapabilities:['market.quote','company.financials']}); assert.equal((await running()).length,0);
  result.checks.push('corrected historic outcome is not replayed');
  await show({...base,id:'all-failed',status:'failed',completedCapabilities:[],failedCapabilities:[...base.plannedCapabilities]});
  assert.equal(await page.locator('[role="progressbar"]').getAttribute('aria-valuenow'),'100');
  assert.ok((await page.locator('.desk-flow-summary').innerText()).includes('4 失败')); assert.equal((await running()).length,0);
  result.checks.push('all failures resolve collection without claiming synthesis success'); await capture('05-all-failed'); await page.waitForTimeout(400);
  result.passed=true; console.log(`PASS actual Electron component motion: ${result.checks.length} checks, ${result.frames.length} frames; not live research`);
} catch(error) { result.error=String(error.stack??error); throw error; }
finally {writeFileSync(join(directory,'report.json'),JSON.stringify(result,null,2));await bounded(application.close(),'close fixture',10000);if(video)await bounded(video.saveAs(join(directory,'flow-motion.webm')),'save video',15000);}
